use ETRADE2
select * from CUSTOMERS
select * from ITEMS
select NAMESURNAME,GENDER,CITY from CUSTOMERS
select CITYNAME,POPULATION  from CITIES 
select GENDER,NAME_ from NAMES
select ID,CITY,TOWN FROM CITY_DISTRICT  
select * from CUSTOMERS WHERE CITY='Bayburts'
select NAMESURNAME,CITY,TELNR FROM CUSTOMERS WHERE CITY IN ('Ankara','İstanbul') ORDER BY NAMESURNAME ASC


SELECT
  CONCAT(first_name, ' ', last_name) AS full_name
FROM patients;

SELECT
  CONCAT(NAME_, ' ', SURNAME) AS full_name
FROM CUSTOMERS;



SELECT * FROM patients
select first_name,last_name,gender	from patients where  gender='M'

select first_name,last_name from patients where allergies is null

select first_name from	 patients WHERE first_name 	like 'C%';

select first_name, last_name from patients where weight between 100 and 120



SELECT
  CONCAT(NAME_, ' ', SURNAME) AS full_name
FROM CUSTOMERS;


INSERT INTO CUSTOMERS (NAMESURNAME,	GENDER,	BIRTHDATE,	CITY,	TOWN,	TELNR,	NAME_,	SURNAME)
VALUES ('Fırat Kaya','E','2000.06.30','Kocaeli','Körfez','05357290460','Fırat','Kaya')   
INSERT INTO CUSTOMERS (NAMESURNAME,	GENDER,	BIRTHDATE,	CITY,	TOWN,	TELNR,	NAME_,	SURNAME)
Values ('Yunus AKGÜN','E','2000.06.30','Kocaeli','Körfez','05357290460','Yunus','AKGÜN') 
INSERT INTO CITIES (CITYNAME,POPULATION ,POPULATIONPERCENT,RANDOMBEG,RANDOMEND,REGION) VALUES('Benşehir',1,1,1,1,'anadolu')
UPDATE Customers
SET Age = 20
WHERE ID =2512014;
UPDATE CUSTOMERS set age = 77 where ID=1;
Update CUSTOMERS SET TOWN ='Ahlat' where ID=1;
UPDATE CUSTOMERS SET SURNAME='KAYA',NAMESURNAME='Yalçın KAYA' WHERE ID=1;
SELECT * FROM CITIES  order by 1 asc
UPDATE CITIES SET ID=82 WHERE CITYNAME='Benşehir'
update patients set allergies='NKA' where allergies IS null

ALTER TABLE	CUSTOMERS ADD AGE int
Alter table kitaplar add Sayfarengi nvarchar(50) 


UPDATE CUSTOMERS
SET AGE=DATEDIFF(YEAR,BIRTHDATE,GETDATE())	
UPDATE CUSTOMERS SET SURNAME='KAYA' WHERE SURNAME='Kaya'
UPDATE CUSTOMERS SET GENDER='ERKEK' WHERE GENDER='E'
UPDATE CUSTOMERS SET AGE=25 WHERE ID=2512014;



DELETE FROM CUSTOMERS 

DELETE FROM CUSTOMERS WHERE CITY='Bayburts'

TRUNCATE TABLE CUSTOMERS  


select * from CUSTOMERS WHERE NAMESURNAME='Fırat Kaya'
select * from CUSTOMERS WHERE CITY='Kocaeli'
select * from CUSTOMERS WHERE CITY='İstanbul'
select * from CUSTOMERS WHERE Not CITY='İstanbul'
select * from CUSTOMERS WHERE  GENDER='E'
select * from CUSTOMERS WHERE BIRTHDATE BETWEEN '19860101' and '20000101'
select * from CUSTOMERS WHERE NAMESURNAME LIKE 'Fırat%'
select * from CUSTOMERS WHERE NAMESURNAME LIKE '%at'
select * from CUSTOMERS WHERE NAMESURNAME LIKE '%YA'
select * from CUSTOMERS WHERE SURNAME LIKE 'KAYA'

select * from CUSTOMERS WHERE NAME_='Fırat' AND CITY='Kocaeli' 
select * from CUSTOMERS WHERE NAME_='Fırat' AND CITY='Kocaeli'  AND TOWN='Körfez'
select * from CUSTOMERS where GENDER='E' AND BIRTHDATE BETWEEN '19900303' AND '19910502'
select * from CUSTOMERS where GENDER='E' AND BIRTHDATE BETWEEN '19900303' AND '19900502' AND TOWN='Körfez'
select * from CUSTOMERS where CITY='Kocaeli' Or CITY='Sakarya'
select * from CUSTOMERS where CITY='Kocaeli' 
select * from CUSTOMERS where  AGE BETWEEN '70' AND '73'
select * from CITIES WHERE POPULATION BETWEEN '5000' anD '100000'
SELECT * FROM CITIES WHERE POPULATIONPERCENT BETWEEN '28' AND '40'
select * from CITIES where POPULATION between '500000' and '1000000'
SELECT * FROM CITIES WHERE POPULATION>='200000'
SELECT * FROM CUSTOMERS WHERE NAME_='Fırat' And TOWN='Körfez' AND AGE Between '20' AND '28'
select * from CUSTOMERS where AGE between '20' AND '28'



select * from CUSTOMERS WHERE CITY IN ('Kocaeli','İstanbul')

select * from CUSTOMERS WHERE CITY IN ('Kocaeli','İstanbul','Kırşehir')

select * from CUSTOMERS WHERE TOWN IN ('Körfez','Kadıköy','Akpınar') 
select * from CUSTOMERS WHERE TOWN IN ('Körfez','Başiskele','Derince') And  Age  Between  '20' And '30' ORDER BY 10 asc 
select * from CUSTOMERS WHERE SURNAME IN ('ENİS','AÇICI')
select * from CUSTOMERS WHERE  AGE IN ('70','71','72')
select * from CUSTOMERS WHERE AGE BETWEEN '40'  AND '50'
select * from CUSTOMERS WHERE CITY='Muş'
select * from CUSTOMERS WHERE NAME_ LIKE 'Fır%'
select * from CUSTOMERS WHERE SURNAME LIKE 'AHMET'
select * from CUSTOMERS WHERE NAME_ IN ('Ahmet','Fırat')
 
select * from ITEMS

select DISTINCT CITY FROM CUSTOMERS
select DISTINCT ITEMNAME from   ITEMS
select DISTINCT TOWN FROM CUSTOMERS WHERE CITY='İstanbul' 
select DISTINCT NAME_ FROM CUSTOMERS WHERE CITY='İstanbul'  
SELECT DISTINCT REGION FROM SALES 




select * from CUSTOMERS ORDER BY ID ASC
select * from CUSTOMERS ORDER BY ID DESC
SELECT * FROM CUSTOMERS ORDER BY AGE DESC
SELECT * FROM CUSTOMERS ORDER BY CITY 
SELECT * FROM CUSTOMERS ORDER BY NAME_
SELECT * FROM CUSTOMERS WHERE CITY='Kocaeli' ORDER BY NAME_ DESC 
select * from customers WHERE CITY='Kocaeli' ORDER BY BIRTHDATE ASC 
select * from customers WHERE CITY='Kocaeli' ORDER BY BIRTHDATE Desc
select * from CUSTOMERS ORDER BY CITY,NAME_ desc
select * from CUSTOMERS ORDER BY 5 
select * from CUSTOMERS ORDER BY 5 DESC
select * from CUSTOMERS WHERE TOWN='Körfez' ORDER BY 5,2



SELECT TOP 100 * from CUSTOMERS ORDER BY AGE
SELECT TOP 200 * FROM CUSTOMERS

SELECT TOP 100 * FROM CUSTOMERS WHERE CITY='Kocaeli' And TOWN='Körfez' ORDER BY 2 DESC
SELECT TOP 500 * FROM CUSTOMERS WHERE BIRTHDATE BETWEEN '19910101' AND '19910102' ORDER BY 2



SELECT * FROM SALES ORDER BY AMOUNT DESC
                                                                          AGGEREGATE

SELECT COUNT(*) FROM SALES ORDER BY AMOUNT
SELECT MIN(AMOUNT),MAX(AMOUNT) FROM SALES
SELECT MAX(PRICE) FROM SALES
SELECT MIN(PRICE) FROM SALES
SELECT DATE_ FROM SALES

SELECT MAX(PRICE),MIN(PRICE) FROM SALES
SELECT MAX(TOTALPRICE),MIN(TOTALPRICE) FROM SALES
SELECT COUNT(FICHENO) FROM SALES
SELECT SUM(AMOUNT) FROM SALES WHERE DATE_ BETWEEN '2019-01-01' AND '2019-05-30'
SELECT AVG(AMOUNT) FROM SALES

SELECT CITY, MAX(PRICE),MIN(PRICE),COUNT(FICHENO),SUM(TOTALPRICE) AS TOPLAM,AVG(TOTALPRICE) FROM SALES GROUP BY CITY ORDER BY TOPLAM   ASC
SELECT  DISTRICT, MAX(PRICE) AS MAKSFİYAT,MIN(PRICE) AS MİNUMUMFİYAT,COUNT(FICHENO) AS ADET,SUM(TOTALPRICE) AS TOPLAM, AVG(TOTALPRICE) AS ORTALAMA FROM SALES GROUP BY DISTRICT
SELECT CITY , MAX(TOTALPRICE)AS MAKSURUNFIYAT ,MIN(TOTALPRICE) AS MINURUNFIYAT,SUM(TOTALPRICE) AS TOPLAMGELIR,AVG(TOTALPRICE) AS ORTALAMAFIYAT FROM SALES GROUP BY CITY ORDER BY TOPLAMGELIR DESC
SELECT FICHENO FROM SALES 
SELECT COUNT(FICHENO) FROM SALES

SELECT REGION, MAX(PRICE),MIN(PRICE),COUNT(FICHENO),SUM(TOTALPRICE) AS TOPLAM,AVG(TOTALPRICE) FROM SALES GROUP BY REGION ORDER BY TOPLAM   DESC

select DISTINCT ITEMNAME FROM SALES
SELECT COUNT(ITEMNAME) FROM SALES
SELECT CITY, MAX(AMOUNT)  AS ENCOKSATILAN ,MIN(AMOUNT)AS ENAZSATILAN FROM SALES GROUP BY CITY
SELECT   CONVERT(DATE,DATE_) AS DATE2 , * FROM SALES
SELECT CONVERT(TIME,DATE_) AS SAAT , * FROM SALES
SELECT DATE_ FROM SALES
Update SALES set DATE2= CONVERT(DATE,DATE_) 
SELECT * FROM SALES
select DATE2,CITY,SUM(TOTALPRICE)  from sales 
WHERE DATE2='2019-08-02' GROUP BY DATE2,CITY

select DATE2,CITY,DISTRICT,SUM(TOTALPRICE) AS TOPLAMSATIS from sales
where DATE2='2019-08-02' GROUP BY DATE2,CITY,DISTRICT ORDER BY SUM(TOTALPRICE) DESC
SELECT DATE2 FROM SALES
SELECT CITY, MONTH(DATE2) AS AY,SUM(TOTALPRICE) AS TOPLAM FROM SALES GROUP BY CITY , MONTH(DATE2)
select DATEPART(MONTH,'2019-08-02')
UPDATE SALES SET MONTHNAME_='01.OCAK' WHERE DATEPART(MONTH,DATE2)=1
UPDATE SALES SET MONTHNAME_='02.ŞUBAT' WHERE DATEPART(MONTH,DATE2)=2
UPDATE SALES SET MONTHNAME_='03.MART' WHERE DATEPART(MONTH,DATE2)=3
UPDATE SALES SET MONTHNAME_='04.NİSAN' WHERE DATEPART(MONTH,DATE2)=4
UPDATE SALES SET MONTHNAME_='05.MAYIS' WHERE DATEPART(MONTH,DATE2)=5
UPDATE SALES SET MONTHNAME_='06.HAZİRAN' WHERE DATEPART(MONTH,DATE2)=6
UPDATE SALES SET MONTHNAME_='07.TEMMUZ' WHERE DATEPART(MONTH,DATE2)=7
UPDATE SALES SET MONTHNAME_='08.AĞUSTOS' WHERE DATEPART(MONTH,DATE2)=8
UPDATE SALES SET MONTHNAME_='09.EYLÜL' WHERE DATEPART(MONTH,DATE2)=9
UPDATE SALES SET MONTHNAME_='10.EKİM' WHERE DATEPART(MONTH,DATE2)=10
UPDATE SALES SET MONTHNAME_='11.KASIM' WHERE DATEPART(MONTH,DATE2)=11
UPDATE SALES SET MONTHNAME_='12.ARALIK' WHERE DATEPART(MONTH,DATE2)=12
SELECT * FROM SALES WHERE DATEPART(MONTH,DATE2)=3
SELECT * FROM SALES WHERE DATEPART(MONTH,DATE2)=6 
SELECT * FROM SALES WHERE DATEPART(YEAR, DATE2) = 2019
select * from SALES where DATEPART(MONTH,DATE2) = 2 AND DATEPART(YEAR, DATE2) = 2019
AND DATEPART(MONTH, DATE2) = 3 
SELECT * FROM SALES WHERE DATEPART(MONTH,DATE2)=11
SELECT DISTINCT CATEGORY1 FROM SALES
SELECT DISTINCT CATEGORY2 FROM SALES
SELECT  CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4, SUM(TOTALPRICE) AS TOPLAMFIYAT, COUNT(*) AS ROWCOUNT_, SUM(AMOUNT) FROM SALES  GROUP BY CATEGORY1,CATEGORY2,CATEGORY3,CATEGORY4




SELECT USERS.*,ADDRESS.ADDRESSTEXT FROM USERS,ADDRESS
WHERE USERS.ID=ADDRESS.USERID AND USERS.ID=4 

SELECT USERS.NAME,SURNAME,ADDRESS.ADDRESSTEXT FROM USERS ,ADDRESS 

SELECT U.NAME,U.SURNAME ,A.ADDRESTEXT,TOWN FROM  USERS U, ADDRES A WHERE U.ID=A.USERID


SELECT   USERS.NAMSURNAME,USERS.EMAIL,COUTRIES.COUNTRY  FROM 
USERS 
JOIN ADDRESS ON ADDRESS.USERID=USERS.ID
JOIN COUNTRIES  ON COUNTRIES.ID=ADDRESS.COUNTRYID

SELECT USERS.NAME,USERS.SURNAME, ADDRESS.CITY
FROM USERS
JOIN ADDRESS ON ADDRESS.USERID = USERS.ID

SELECT USERS.NAME, ADDRESS.CITY
FROM USERS
JOIN ADDRESS ON ADDRESS.USERID = USERS.ID


SELECT COUNTRIES.COUNTRY, COUNT(DISTINCT USERS.ID)  FROM 
USERS 
JOIN ADDRESS ON ADDRESS.USERID=USERS.ID
JOIN COUNTRIES  ON COUNTRIES.ID=ADDRESS.COUNTRYID
GROUP BY COUNTRIES.COUNTRY         -----------

USE TEST1
SELECT * FROM USERS
SELECT * FROM ADDRESS
SELECT U.USERNAME_,A.ADDRESSTEXT FROM USERS U
JOIN ADDRESS A ON A.USERID=U.ID


SELECT USERS.USERNAME_,ADDRESS.ADDRESSTEXT FROM  USERS JOIN ADDRESS ON USERS.ID=ADDRESS.USERID
SELECT U.USERNAME_,A.ADDRESSTEXT FROM USERS U LEFT JOIN ADDRESS A  ON U.ID=A.USERID

use ETRADE4
SELECT U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,CT.CITY AS IL ,T.TOWN AS ILCE ,D.DISTRICT AS SEMT ,A.ADDRESSTEXT AS ACIKADRES  FROM ORDERS O
INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID   
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
WHERE U.NAMESURNAME='Oğuz Çankırılı'
 SELECT * FROM ORDERDETAILS 
  SELECT * FROM INVOICEDETAILS
   SELECT * FROM INVOICES
   SELECT * FROM USERS 
   SELECT * FROM ADDRESS 
   SELECT * FROM INVOICES
   SELECT * FROM ORDERS


SELECT U.USERNAME_ AS KULLANICIADI, U.NAMESURNAME AS ADSOYAD,CT.CITY , O.DATE_, I.CARGOFICHENO , O.TOTALPRICE   FROM ORDERS O
INNER JOIN USERS U ON O.USERID=U.ID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN INVOICES I ON I.ORDERID=O.ID

SELECT U.USERNAME_ AS KULLANICIADI,U.NAMESURNAME AS ADSOYAD,CT.CITY AS IL ,T.TOWN AS ILCE ,D.DISTRICT AS SEMT ,A.ADDRESSTEXT AS ACIKADRES ,
O.ID AS SIPARISID,O.DATE_ AS TARIH , O.TOTALPRICE AS TOPLAMTUTAR ,OD.* ,ITM.*,
ITM.ITEMCODE AS URUNKODU, ITM.ITEMNAME AS URUNADI ,OD.AMOUNT AS MIKTAR,OD.UNITPRICE AS BIRIMFIYAT,OD.LINETOTAL AS SATIRTOPLAMI
FROM ORDERS O

INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID   
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID
WHERE O.ID=1 --NAMESURNAME='Selma YÜZÜGÜLLÜER'
SELECT ID FROM ORDERS

--------- ŞEHİRLERE GÖRE YAPILAN SİPARİŞ TUTAR,ADET VE SAYILARI 
SELECT CT.CITY , SUM(OD.LINETOTAL) AS TOPLAMSIPARIŞTUTARI ,   SUM(OD.AMOUNT) AS TOPLAMSIPARISADEDI ,COUNT(OD.ID) AS TOPLAMSIPARISAYISI FROM ORDERS O

INNER JOIN USERS U ON U.ID=O.USERID
INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN TOWNS T ON T.ID=A.TOWNID   
INNER JOIN DISTRICTS D ON D.ID=A.DISTRICTID
INNER JOIN PAYMENTS P ON P.ORDERID=O.ID
INNER JOIN INVOICES I ON I.ORDERID=O.ID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
INNER JOIN ITEMS ITM ON ITM.ID=OD.ITEMID

GROUP BY CT.CITY
ORDER BY sum(OD.LINETOTAL) desc

 
 SELECT CT.CITY,sum(OD.AMOUNT), sum(OD.LINETOTAL)/COUNT(DISTINCT O.ID) AS SEPETORTALAMASI FROM ORDERS O

INNER JOIN ADDRESS A ON A.ID=O.ADDRESSID
INNER JOIN CITIES CT ON CT.ID=A.CITYID
INNER JOIN ORDERDETAILS OD ON OD.ORDERID=O.ID
GROUP BY CT.CITY 
HAVING  SUM(OD.LINETOTAL)>=10000




